# Generated by Django 2.1.5 on 2019-01-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.AutoField(help_text='Unique ID of alarm', primary_key=True, serialize=False)),
                ('user', models.CharField(help_text='User', max_length=20)),
                ('alarm', models.DateTimeField()),
            ],
        ),
    ]
